### ISSUE TITLE
Option for sending username/password

### ISSUE THREAD

**Issue by kevinpurdy** [philprobinson84/home-assistant-ds18b20#1]
The newest versions of Mosquitto, and the Mosquitto broker on HA, disallow anonymous connections without username/password. One of many threads on this: https://github.com/home-assistant/addons/issues/2483

Would it be possible to have this (very useful!) app send a user/pass along with the temperature payload?

**Comment by philr-biz** [comment]
@kevinpurdy thanks for your message, and your interest in this project!

I haven't been keeping my HA instance up to date (no remote access, so not a huge concern for me) and was unaware of this change.

I'll plan some time over the next 2 weeks to enable username/password authentication for MQTT, and at the same time will move these and other settings to a config file to remove the need to edit python code with details of the MQTT broker.
